version: "3.8"
services:
  socket-server:
    build: ./socket-server
    container_name: socket-server
    environment:
      - PORT=3002
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - REDIS_URL=redis://redis:6379
      - GEMINI_API_KEY=
    ports:
      - "3002:3002"
    volumes:
      - ./socket-server:/app
      - /app/node_modules
    depends_on:
      - db
      - redis
    command: npm run docker:dev

  db:
    image: postgres:latest
    container_name: db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  redis:
    image: redis:latest
    container_name: redis
